### ISSUE TITLE
enhance video player with play button over the poster

### ISSUE THREAD

**Issue by ui-guys** [Uiseguys/stencil-bs-ui-lib#65]
https://stencil-bs.herokuapp.com/
Current behaviour of video player:

the user sees first the image he has defined as "poster" property on the <fcl-video-player /> component. When the user clicks on the poster the poster is hidden and the user sees the video which is auto-playing. That's also correct.

Please add on top of the poster image a play button, so the user actually sees that it's a video player.

**Comment by divsbhalala** [comment]
Here is the PR for that 
https://github.com/Uiseguys/stencil-bs-ui-lib/pull/66
