### ISSUE TITLE
Enhancement for DND Component.

### ISSUE THREAD

**Issue by ui-guys** [Uiseguys/stencil-bs-ui-lib#98]
Following Use Case:
In an application I render a list of some items belonging to an object, let's say videos on a playlist.
Now I want the user to be able to re-order the videos and save that new ordered list.

With the information in the events currently exposed by the component it is very hard to reorder the original array of items.

To facilitate the usage in such a case, the cwc-dnd component should be enhanced as follows:

*value*: an array (or array of arrays if more coumns)
*change* gives back the changed array (or array of arrays)

value and change properties are optional and are *not* influencing the rendering or order of the child dom elements.

the given data structure just reflects the sorting of the html elements.

**Comment by AlexanderSergan** [comment]
Closing with #103
